[package]
name = "jmap_sharing"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
jmap = { path = "../jmap" }
jmap_mail = { path = "../jmap_mail" }
store = { path = "../store" }
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
argon2 = "0.4.0"
