[package]
name = "jmap-server"
version = "0.1.0"
edition = "2018"

[dependencies]
nlp = { path = "components/nlp" }
jmap = { path = "components/jmap" }
jmap_mail = { path = "components/jmap_mail" }
store = { path = "components/store" }
store_rocksdb = { path = "components/store_rocksdb" }
actix-web = "4"
openssl = "0.10"
tracing-subscriber = "0.2"
serde = { version = "1.0", features = ["derive"]}
gethostname = "0.2.2"
rand = "0.8.5"
tokio = { version = "1.16.1", features = ["full"] }
tokio-util = "0.7.0"
num_cpus = "1.13.1"
futures = "0.3"
rayon = "1.5.1"

[dev-dependencies]
store_test = { path = "components/store_test" }

[workspace]
resolver = "2"
members = [
    "components/nlp",
    "components/store",
    "components/store_rocksdb",
    "components/store_test",
    "components/jmap",
    "components/jmap_mail",
]

[profile.dev]
opt-level = 0
debug = 1
codegen-units = 4
lto = false
incremental = true
panic = 'unwind'
debug-assertions = true
overflow-checks = false
rpath = false

[profile.release]
opt-level = 3
debug = false
codegen-units = 1
lto = "thin"
incremental = false
panic = 'unwind'
debug-assertions = false
overflow-checks = false
rpath = false

#[profile.release.package.server]
#opt-level = 1
#codegen-units = 4

[profile.test]
opt-level = 0
debug = 1
codegen-units = 16
lto = false
incremental = true
debug-assertions = true
overflow-checks = true
rpath = false

[profile.bench]
opt-level = 3
debug = false
codegen-units = 1
lto = 'thin'
incremental = false
debug-assertions = false
overflow-checks = false
rpath = false
