[package]
name = "jmap-server"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
core = { path = "components/core" }
store = { path = "components/store" }
store_rocksdb = { path = "components/store_rocksdb" }
tracing-subscriber = "0.2"

[dev-dependencies]
jmap = { path = "components/jmap" }
jmap_mail = { path = "components/jmap_mail" }
core = { path = "components/core", features = ["debug"] }
csv = "1.1"
flate2 = { version = "1.0.17", features = ["zlib"], default-features = false }
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
serde_yaml = "0.8"
tokio-test = "0.4"

[workspace]
members = [
    "components/core",
    "components/store",
    "components/store_rocksdb",
    "components/jmap",
    "components/jmap_mail",
]

[profile.dev]
opt-level = 0
debug = 1
codegen-units = 4
lto = false
incremental = true
panic = 'unwind'
debug-assertions = true
overflow-checks = false
rpath = false

[profile.release]
opt-level = 3
debug = false
codegen-units = 1
lto = "thin"
incremental = false
panic = 'unwind'
debug-assertions = false
overflow-checks = false
rpath = false

#[profile.release.package.server]
#opt-level = 1
#codegen-units = 4

[profile.test]
opt-level = 0
debug = 1
codegen-units = 16
lto = false
incremental = true
debug-assertions = true
overflow-checks = true
rpath = false

[profile.bench]
opt-level = 3
debug = false
codegen-units = 1
lto = 'thin'
incremental = false
debug-assertions = false
overflow-checks = false
rpath = false
