[package]
name = "jmap_mail"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
nlp = { path = "../nlp" }
jmap = { path = "../jmap" }
store = { path = "../store" }
mail-parser = { git = "https://github.com/stalwartlabs/mail-parser" }
mail-builder = { git = "https://github.com/stalwartlabs/mail-builder" }
chrono = "0.4"
serde = { version = "1.0", features = ["derive"]}
rmp-serde = "1.0.0"
