[package]
name = "jmap_mail"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
nlp = { path = "../nlp" }
store = { path = "../store" }
mail-parser = { path = "/home/vagrant/code/mail-parser" }
chrono = "0.4"
lz4_flex = "0.9.2"
serde = { version = "1.0", features = ["derive"]}
bincode = "1.3.3"
