[package]
name = "jmap"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
store = { path = "../store" }
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
base64 = "0.13"
scrypt =  "0.10"
