[package]
name = "jmap"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
store = { path = "../store" }
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
rmp-serde = "1.0.0"
