[package]
name = "store_rocksdb"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
store = { path = "../store" }
rocksdb = "0.18"

#[dev-dependencies]
store_test = { path = "../store_test" }


