[package]
name = "store"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
nlp = { path = "../nlp" }
bitpacking = "0.8.4"
serde = { version = "1.0", features = ["derive"]}
parking_lot = "0.12.0"
bincode = "1.3.3"
futures = "0.3"
rayon = "1.5.1"
moka = { version = "0.7", features = ["future"] }
num_cpus = "1.13.1"
tokio = { version = "1.16.1", features = ["full"] }
roaring = "0.9"
base32 = "0.4.0"
sha2 = "0.10.1"
tracing = "0.1"
